# Generated by Django 3.1.1 on 2020-09-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
        ('tourist_point', '0002_auto_20200925_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristpoint',
            name='attractions',
            field=models.ManyToManyField(to='attractions.Attractions'),
        ),
    ]
