# Generated by Django 3.1.1 on 2020-09-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentreview', '0001_initial'),
        ('tourist_point', '0003_touristpoint_attractions'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristpoint',
            name='comment',
            field=models.ManyToManyField(to='commentreview.CommentReview'),
        ),
    ]
