# Generated by Django 3.1.1 on 2020-09-28 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('tourist_point', '0006_touristpoint_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristpoint',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.location'),
        ),
    ]
