# Generated by Django 3.1.1 on 2020-09-28 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('tourist_point', '0007_auto_20200928_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristpoint',
            name='location',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='location.location'),
            preserve_default=False,
        ),
    ]
